### PR TITLE
Pin *all* the versions!

### LINKED ISSUE #56: Define project toolchain in `rust-toolchain.toml`
## What problem does this solve or what need does it fill?

Some people have `nightly` set as their default toolchain, but we use `stable` in CI.
This might cause inconsistencies with compile errors and clippy warnings that are generated locally vs. in the CI.

## What solution would you like?

Create a top-level `rust-toolchain.toml` file with the following content:
```toml
[toolchain]
channel = "stable"
```

## What alternative(s) have you considered?

Of course it's possible to set the toolchain using command overrides like `cargo +stable check` or `rustup override set stable`.

Personally I think it's better to define this directly in the source to avoid unintended behavior. I personally already encountered a clippy warning difference between CI and my local setup due to different toolchains.

## Additional context

Documentation on Rust toolchain overrides: <https://rust-lang.github.io/rustup/overrides.html>

### PR DESCRIPTION
**Pull request by CobaltCause**
# Objective

Fixes #56, progresses towards #59 too.

## Tasks

* [X] Add `rust-toolchain.toml`
* [X] Add Nix Flake
* [X] Use Flake and `rust-toolchain.toml` in CI
* [X] Document Nix usage
* ~~Make `cargo run -p gentest` work under Nix?~~ https://github.com/DioxusLabs/sprawl/issues/65

## Context

I tried to write detailed commit messages, so you can check there for details about what's doing what.

### CI changes

I made a few small additions to tasks run as part of CI (`nixpkgs-fmt`, `shellcheck`, and `shfmt`); if we don't want those I can remove them.

### Documentation

I'm not quite sure how much depth to go into for Nix documentation.

### Nix usability

`cargo run -p gentest` doesn't work under Nix right now. Even after adding the required packages:

```diff
diff --git a/flake.nix b/flake.nix
index 086d9a1..b5046d4 100644
--- a/flake.nix
+++ b/flake.nix
@@ -51,14 +51,21 @@
         RUST_SRC_PATH = "${rust-toolchain}/lib/rustlib/src/rust/library";

         nativeBuildInputs = (with pkgs; [
+          chromedriver
+          chromium
           file
           ncurses
           nixpkgs-fmt
+          pkg-config
           shellcheck
           shfmt
         ]) ++ (with pkgs.nodePackages; [
           markdownlint-cli
         ]);
+
+        buildInputs = (with pkgs; [
+          openssl.dev
+        ]);
       };

       checks = {
```

This `unwrap` panics: https://github.com/DioxusLabs/sprawl/blob/7e84a464bb82e8ed9056bf51e944b91650f38f5d/scripts/gentest/src/main.rs#L173

I'm not sure if this is a Nix problem or not. I haven't committed this change for now since it'll pull in a lot of dependencies that might not be necessary, especially considering it doesn't seem to be working. This is probably worthy of a separate issue if it's a general problem and isn't Nix-related.

### CODE REVIEW

**Comment by TimJentzsch** [comment]
Is the error with the gentests the same as the one in <https://github.com/DioxusLabs/sprawl/discussions/46#discussion-4077754>?

**Review by TimJentzsch — COMMENTED** [review]
I just did a first review pass and I think it looks promising.
Being able to easily run CI locally is definitely nice to have.

Some concerns might be that the CI script is harder to read and understand than the usual GitHub action setup. That might make it harder to make changes in the future.
It also makes the initial dev setup more difficult as you need to install additional dependencies. This can be okay though, since it's an optional step.

Later today I will take another look at this and try the setup on my local machine.

PS: I love the detailed commit messages, great job!

**Comment by CobaltCause** [comment]
Thanks for the feedback, all. I find the comments about CI script readability to be mildly interesting: personally, I feel like Bash is easier to work with since it's the same everywhere, as opposed to platform-specific CI configuration files; though apparently I'm in the minority here, which is fine although unexpected.

---

> Is the error with the gentests the same as the one in [#46 (comment)](https://github.com/DioxusLabs/sprawl/discussions/46#discussion-4077754)?

No, this looks to be different than that. I'll add a comment on that thread with the full output.

---

Just to clarify, @alice-i-cecile's fifth point is indeed true, this does run the checks in sequence. I don't personally find this to be that much of an issue, since running CI locally with these changes is quite easy and very fast, but I do agree that CI taking longer in general is a legitimate drawback. 

---

In general it seems like the direction this PR should go is pretty well decided. I'll wait for @TimJentzsch to get a chance to try this out locally, and after that, I can drop all the commits other than the first one, and from there we can bikeshed the decisions in `rust-toolchain.toml` if need be. (I chose the `minimal` profile with `rustfmt`, `clippy`, and `rust-src` because stable users on the `default` profile already have `rust-docs` and nightly users can use the nightly version, and `rust-src` is needed so that `rust-analyzer` is able to reference the right toolchain.)

**Comment by mockersf** [comment]
my feelings on this PR (in the order of the files changed in review view):
* running all CI in only one step is bad for granularity. When it fails, you end up having one gigantic log to read, instead of one specific to your failure
* nix seems a lot more complicated to setup than I expected. In particular, expecting people to do everything through a CLI is not good
* committing the lock file for a library is bad. It's a pain to keep updated, and it's not used when someone uses this library, so it would just lead to contributors of this repo stuck on old versions that would not be what users are using
* bash is really not a nice language, I prefer to not have control flow in it
* `rust-toolchain.toml` are not really meant to be used to target stable. Sure they can, but their point is more to pin on a given nightly, it feels strange to use one for stable. Admittedly, I don't understand why so many Rust users are still using a nightly version as their default. It used to make sense a few years back, but not anymore in my experience. Also, as this file is only used for contributors to this repo, nightly should still be tested if that's a use case that is supported

**Comment by CobaltCause** [comment]
> one gigantic log to read, instead of one specific to your failure

To me it seems like the strategy for reading logs is always to start at the bottom and go backwards, which you have to do for individual-tool CI passes anyway when they have a lot of output (e.g. `cargo clippy` for projects with lots of dependencies); so the process of discovering what went wrong feels pretty much identical to me regardless.

> Admittedly, I don't understand why so many Rust users are still using a nightly version as their default. It used to make sense a few years back, but not anymore in my experience.

I'm kind of in the same boat here, but it's so trivial to support this that we may as well.

> nightly should still be tested if that's a use case that is supported

Yep: https://github.com/DioxusLabs/sprawl/issues/59

---

Keep in mind that Nix is completely optional, and also that the majority of this PR is highly likely going to be reverted anyway:

> In general it seems like the direction this PR should go is pretty well decided. [...] I can drop all the commits other than the first one [...]

**Comment by TimJentzsch** [comment]
> rust-toolchain.toml are not really meant to be used to target stable. Sure they can, but their point is more to pin on a given nightly, it feels strange to use one for stable. Admittedly, I don't understand why so many Rust users are still using a nightly version as their default. It used to make sense a few years back, but not anymore in my experience. Also, as this file is only used for contributors to this repo, nightly should still be tested if that's a use case that is supported

The main reason I suggested that was because the stable version had a clippy lint that nightly did not have, which then caused CI to fail. Of course it's easy to switch back to stable for the crate, but having it configured to be the same as CI by default is nice to have IMO.

**Comment by CobaltCause** [comment]
Alright, I've rebased away the Nix things. If anyone's curious in trying that stuff out still, have a look at [this](https://github.com/CobaltCause/ghat).

**Review by alice-i-cecile — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
Thanks :) Don't worry about it, this was a productive exploration.

**Pull request merged**
